name: ejeapp
description: "A new Flutter project."

publish_to: 'none'

version: "1.1.0"

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  meta: ^1.16.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true