// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy3Nw53alIsLlfN0-cUgi8Yqlrkx7ess0',
    appId: '1:670952889394:web:f8e1abe4bd35ee9888702b',
    messagingSenderId: '670952889394',
    projectId: 'photoapp-a4f6b',
    authDomain: 'photoapp-a4f6b.firebaseapp.com',
    storageBucket: 'photoapp-a4f6b.firebasestorage.app',
    measurementId: 'G-KF4EH6BD6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFItzTxdEcJCVwgqVU66OotvORMxukGzQ',
    appId: '1:670952889394:android:14cdc682c31e624d88702b',
    messagingSenderId: '670952889394',
    projectId: 'photoapp-a4f6b',
    storageBucket: 'photoapp-a4f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyUJEO48VmW0PZrUFoh6y1QwkLeoPIFY',
    appId: '1:670952889394:ios:f513649d0eeba80b88702b',
    messagingSenderId: '670952889394',
    projectId: 'photoapp-a4f6b',
    storageBucket: 'photoapp-a4f6b.firebasestorage.app',
    iosBundleId: 'com.example.ejeapp',
  );
}
